### PR TITLE
Feat/adding bill metrics

### PR DESCRIPTION
**Pull request by paologallinaharbur**
Added new metrics `github_workflow_usage `:
```
# HELP github_workflow_usage Number of billable seconds used by a specific workflow during the current billing cycle. Any job re-runs are also included in the usage. Only apply to workflows in private repositories that use GitHub-hosted runners.
# TYPE github_workflow_usage gauge
github_workflow_usage_seconds{id="2862037",name="Create Release",node_id="MDg6V29ya2Zsb3cyODYyMDM3",repo="xxx/xxx",state="active",os="MACOS"} 0
github_workflow_usage_seconds{id="2862037",name="Create Release",node_id="MDg6V29ya2Zsb3cyODYyMDM3",repo="xxx/xxx",state="active",os="UBUNTU"} 706.609
github_workflow_usage_seconds{id="2862037",name="Create Release",node_id="MDg6V29ya2Zsb3cyODYyMDM3",repo="xxx/xxx",state="active",os="WINDOWS"} 7193.223
```

### CODE REVIEW

**Comment by paologallinaharbur** [comment]
@Labbs I added some metrics, I was thinking to add as well in the future pagination support and at least an histogram reporting the time taken by the jobs to run. What do you think?

**Comment by Labbs** [comment]
The pagination against which metrics?
Otherwise to add more metrics, no worries.

**Comment by paologallinaharbur** [comment]
As far as I understand currently the exporter is fetching data without dealing with pagination, therefore if there are too many jobs or runs those will be not fetched.

```
The GitHub API provides a vast wealth of information for developers to consume. Most of the time, you might even find that you're asking for too much information, and in order to keep our servers happy, the API will automatically paginate the requested items.
```

**Comment by Labbs** [comment]
ah yes exact. I just tested and the API returns 25 runs (for +16k runs).

The max result per page is 100.
The paginate option is limited to a part of API:
- list runs
- list runners
- list workflows
- list workflow runs
- list jobs

**Review by srl295 — APPROVED** [review]
I don't have these, but lgtm

**Review by Labbs — APPROVED** [review]

**Pull request merged**
